name: Silakka
favicon: null
layout_spectrum: 0.5012233138550073
typography_spectrum: 0.030903826002031565
title: Pelastusalus Silakka
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1a1819'
    - '#f8faf9'
    - '#81b4df'
    - '#0266ae'
    - '#545b61'
  brandStrength: 0.24773561558686197
  lightness: 0.5162315515335649
  saturation: 0.5164280338212848
  rhythmicContrast: 0.16679495526477695
purpose: []
